name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  # AQUI ESTÁ O DESTAQUE DO SCOPE
  - type: dropdown
    id: scope
    attributes:
      label: Which tool is affected? (Scope)
      description: Please select the specific tool where you found the bug. This is critical for us.
      options:
        - "scope: charts"
        - "scope: live"
        - "scope: counter"
        - "scope: matcher"
        - "scope: shared"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I click the generate button...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: input
    id: user
    attributes:
      label: Last.fm Username (Optional)
      description: If relevant, provide the username used during the error.
      placeholder: snw-mint
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context (Browser, OS, etc)
      description: E.g., Chrome 90, iOS 14.
    validations:
      required: false